version: '3.1'

services:
  mariaDb:
    image: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_USER: admin
      MARIADB_PASSWORD: 1234
      MARIADB_DATABASE : ciberseguridad
    ports:
      - "3307:3306"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d


  servicio-ciberseguridad:
    image: imagenciberseguridad:latest
    container_name: servicio-ciberseguridad
    ports:
      - "8081:8081"
    depends_on:
      - mariaDb